#!/usr/bin/env bun
/// <reference types="bun" />
import { $ } from 'bun';

// Dumps the current database schema (structure only, no data) to
// schema.sql so the full schema is a single git-trackable snapshot.
//
// pg_dump isn't required on the host: we exec it inside the running
// Postgres container (its version matches the server exactly).
//
// Override the container name with PG_CONTAINER if yours differs.

const OUT_FILE = 'schema/schema.sql';

const databaseUrl = Bun.env.DATABASE_URL;
if (!databaseUrl) {
  console.error('DATABASE_URL is not set (see .env.example).');
  process.exit(1);
}

// Parse credentials/db out of the URL so we invoke pg_dump correctly.
const url = new URL(databaseUrl);
const user = decodeURIComponent(url.username) || 'postgres';
const dbName = url.pathname.replace(/^\//, '') || user;

// Find the Postgres container: explicit override, else the compose service.
async function resolveContainer(): Promise<string> {
  const override = Bun.env.PG_CONTAINER;
  if (override) return override;

  // Prefer the compose service container for this project.
  const byService =
    (await $`docker compose ps -q postgres`.nothrow().text()).trim();
  if (byService) return byService;

  // Fallback: any running container whose image looks like postgres.
  const byImage = (
    await $`docker ps --filter ancestor=postgres --format {{.Names}}`
      .nothrow()
      .text()
  )
    .trim()
    .split('\n')
    .filter(Boolean)[0];
  if (byImage) return byImage;

  throw new Error(
    'Could not find a running Postgres container. Start it (docker compose up -d postgres) or set PG_CONTAINER.',
  );
}

const container = await resolveContainer();

// --schema-only: structure, no data. --no-owner/--no-privileges keep the
// dump portable. --exclude-table drops the migrator's internal bookkeeping
// table so schema.sql reflects only the application schema.
const raw = await $`docker exec ${container} pg_dump \
  --username=${user} \
  --schema-only --no-owner --no-privileges \
  --no-comments \
  --exclude-table=_migrations \
  ${dbName}`
  .nothrow()
  .text();

if (!raw.trim()) {
  console.error('pg_dump produced no output — is the database reachable?');
  process.exit(1);
}

// Strip pg_dump boilerplate so the file shows only the real DDL:
//  - psql meta-commands (\restrict, \unrestrict)
//  - session SET / SELECT set_config directives
//  - the dashed comment banners and "PostgreSQL database dump" headers
const dump = raw
  .split('\n')
  .filter((line) => {
    const t = line.trim();
    if (t === '') return true; // keep blank lines for readability
    if (t.startsWith('\\')) return false; // \restrict / \unrestrict
    if (/^SET\s/.test(t)) return false;
    if (/^SELECT pg_catalog\.set_config/.test(t)) return false;
    if (t.startsWith('--')) return false; // comment banners
    return true;
  })
  .join('\n')
  // collapse 3+ blank lines left behind into a single blank line
  .replace(/\n{3,}/g, '\n\n')
  .trim();

const header = `-- Auto-generated by scripts/dump-schema.ts (bun run db:dump).
-- Do not edit by hand — regenerated after every db:up / db:down.
-- Reflects the current database schema (structure only, no data).

`;

await Bun.write(OUT_FILE, header + dump);
console.log(`Wrote ${OUT_FILE} (${dump.split('\n').length} lines)`);
